### ISSUE TITLE
macsypy.error.MacsypyError: unable to parse model definition 'TXSScan/bacteria/diderm/T2SS'

### ISSUE THREAD

**Issue by yayahoho1** [macsy-models/TXSScan#3]
Hi, i used TXSScan-1.1.0 for my reasearch work, but  i got the error:

macsypy.error.MacsypyError: unable to parse model definition 'TXSScan/bacteria/diderm/T2SS' : The model definition T2SS.xml has an unknown attribute 'multi_model' for a gene. Please fix the definition.

###########
my Macsyfinder version:

> Macsyfinder 2.0rc6
> using:
> - Python 3.7.13 (default, Mar 29 2022, 02:18:16)  [GCC 7.5.0]
> - NetworkX 2.6.3
> 
> MacsyFinder is distributed under the terms of the GNU General Public License (GPLv3).
> See the COPYING file for details.
> 
> If you use this software please cite:
> Abby SS, Néron B, Ménager H, Touchon M, Rocha EPC (2014)
> MacSyFinder: A Program to Mine Genomes for Molecular Systems with an Application to CRISPR-Cas Systems.
> PLoS ONE 9(10): e110726. doi:10.1371/journal.pone.0110726
> 
> and don't forget to cite models used:
> macsydata cite <model>

################

please help me to fix the issue.

Thank you in advance.

**Comment by rdenise** [comment]
Hi, it is because you need to use the more updated version of macsyfinder (Macsyfinder 2.0rc7 or above)

**Comment by yayahoho1** [comment]
I updated the version of macsyfinder and it works well. Thanks for the help!

**Comment by rdenise** [comment]
You might also have an issue with the version Macsyfinder 2.0rc7 as it is explained on this issue of macsyfinder: https://github.com/gem-pasteur/macsyfinder/issues/52.
